# **Part 1: Data** **Cleaning**

In [1]:
import pandas as pd

df = pd.read_csv('/content/clothing_sales_with_size.csv')

In [2]:

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          497 non-null    float64
 1   Date              498 non-null    object
 2   Customer_Name     498 non-null    object
 3   Product_Category  500 non-null    object
 4   Product_Name      500 non-null    object
 5   Size              497 non-null    object
 6   Quantity          498 non-null    float64
 7   Unit_Price        500 non-null    float64
 8   Total_Sales       498 non-null    float64
 9   Payment_Method    499 non-null    object
 10  Region            498 non-null    object
dtypes: float64(4), object(7)
memory usage: 43.1+ KB

np.int64(0)

In [4]:

df = df.drop_duplicates()
df

,Order_ID,Date,Customer_Name,Product_Category,Product_Name,Size,Quantity,Unit_Price,Total_Sales,Payment_Method,Region
0,1001.0,2026-05-08,Vivaan Nair,Clothing,Jacket,M,4.0,85.0,340.0,Cash,North
1,1002.0,2026-05-18,Rahul Reddy,Clothing,Jacket,XXL,1.0,85.0,85.0,UPI,East
2,1003.0,2026-01-26,Priya Nair,Clothing,Jeans,M,1.0,40.0,40.0,Cash,north
3,1004.0,2026-04-20,Rohan Patel,Clothing,Jacket,XXL,3.0,85.0,255.0,Debit Card,North
4,1005.0,2026-02-28,Rahul Singh,Clothing,Dress,XL,1.0,45.0,45.0,UPI,West
...,...,...,...,...,...,...,...,...,...,...,...
495,1496.0,2026-01-30,Diya Das,Clothing,Sneakers,L,2.0,65.0,130.0,Credit Card,North
496,1497.0,2026-05-03,Isha Nair,Clothing,Dress,M,5.0,45.0,225.0,Debit Card,North
497,1498.0,2026-02-06,Priya Das,Clothing,Socks Pack,S,5.0,8.0,40.0,Debit Card,North
498,1499.0,2026-03-12,Meera Gupta,Clothing,Hoodie,M,4.0,50.0,200.0,Cash,South
499,1500.0,2026-03-01,Kavya Das,Clothing,Dress,XXL,4.0,45.0,180.0,UPI,East

In [9]:
df_clean = df.dropna()
df = df.dropna(subset=['Order_ID'])
df

,Order_ID,Date,Customer_Name,Product_Category,Product_Name,Size,Quantity,Unit_Price,Total_Sales,Payment_Method,Region
0,1001.0,2026-05-08,Vivaan Nair,Clothing,Jacket,M,4.0,85.0,340.0,Cash,North
1,1002.0,2026-05-18,Rahul Reddy,Clothing,Jacket,XXL,1.0,85.0,85.0,UPI,East
2,1003.0,2026-01-26,Priya Nair,Clothing,Jeans,M,1.0,40.0,40.0,Cash,north
3,1004.0,2026-04-20,Rohan Patel,Clothing,Jacket,XXL,3.0,85.0,255.0,Debit Card,North
4,1005.0,2026-02-28,Rahul Singh,Clothing,Dress,XL,1.0,45.0,45.0,UPI,West
...,...,...,...,...,...,...,...,...,...,...,...
495,1496.0,2026-01-30,Diya Das,Clothing,Sneakers,L,2.0,65.0,130.0,Credit Card,North
496,1497.0,2026-05-03,Isha Nair,Clothing,Dress,M,5.0,45.0,225.0,Debit Card,North
497,1498.0,2026-02-06,Priya Das,Clothing,Socks Pack,S,5.0,8.0,40.0,Debit Card,North
498,1499.0,2026-03-12,Meera Gupta,Clothing,Hoodie,M,4.0,50.0,200.0,Cash,South
499,1500.0,2026-03-01,Kavya Das,Clothing,Dress,XXL,4.0,45.0,180.0,UPI,East

In [12]:

df_clean = df.dropna()
df

,Order_ID,Date,Customer_Name,Product_Category,Product_Name,Size,Quantity,Unit_Price,Total_Sales,Payment_Method,Region
0,1001.0,2026-05-08,Vivaan Nair,Clothing,Jacket,M,4.0,85.0,340.0,Cash,North
1,1002.0,2026-05-18,Rahul Reddy,Clothing,Jacket,XXL,1.0,85.0,85.0,UPI,East
2,1003.0,2026-01-26,Priya Nair,Clothing,Jeans,M,1.0,40.0,40.0,Cash,north
3,1004.0,2026-04-20,Rohan Patel,Clothing,Jacket,XXL,3.0,85.0,255.0,Debit Card,North
4,1005.0,2026-02-28,Rahul Singh,Clothing,Dress,XL,1.0,45.0,45.0,UPI,West
...,...,...,...,...,...,...,...,...,...,...,...
495,1496.0,2026-01-30,Diya Das,Clothing,Sneakers,L,2.0,65.0,130.0,Credit Card,North
496,1497.0,2026-05-03,Isha Nair,Clothing,Dress,M,5.0,45.0,225.0,Debit Card,North
497,1498.0,2026-02-06,Priya Das,Clothing,Socks Pack,S,5.0,8.0,40.0,Debit Card,North
498,1499.0,2026-03-12,Meera Gupta,Clothing,Hoodie,M,4.0,50.0,200.0,Cash,South
499,1500.0,2026-03-01,Kavya Das,Clothing,Dress,XXL,4.0,45.0,180.0,UPI,East

In [16]:

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [18]:

df = df.rename(columns={'old_name': 'new_name', 'Salary USD': 'salary'})

In [19]:

df.to_csv('cleaned_dataset.csv', index=False)

# **Part 2: The 10 Sales Questions & Answers**

# **Question 1: How many missing (null) values exist in each column of the dataset, and what is the best strategy (dropping vs. imputation) to handle them without losing critical sales data?**

In [6]:
df = pd.read_csv('/content/cleaned_dataset (1).csv')
print("Missing values count:")
print(df.isnull().sum())

Missing values count:
Order_ID            0
Date                6
Customer_Name       2
Product_Category    0
Product_Name        0
Size                3
Quantity            2
Unit_Price          0
Total_Sales         2
Payment_Method      0
Region              2
dtype: int64

# **Question 2: Are there case-sensitivity or formatting issues causing duplicate categories in columns like Product_Name, Region, and Payment_Method? How can we programmatically standardize them?**

In [7]:
print("Unique Products:", df['Product_Name'].unique())
print("Unique Regions:", df['Region'].unique())


df['Product_Name'] = df['Product_Name'].str.capitalize()
df['Region'] = df['Region'].str.capitalize()
df['Payment_Method'] = df['Payment_Method'].str.upper()

Unique Products: ['Jacket' 'Jeans' 'Dress' 'Sneakers' 'T-Shirt' 'Hoodie' 'Socks Pack'
 'jacket' 'sneakers']
Unique Regions: ['North' 'East' 'north' 'West' 'west' 'South' nan]

# **Question 3: Are there any rows where the Quantity or Total_Sales columns contain negative numbers or zeros? How do these anomalies affect our overall calculations, and how can we filter them out?**

In [8]:

anomalies = df[df['Quantity'] <= 0]
print(f"Number of rows with invalid quantities: {len(anomalies)}")


df_cleaned = df[df['Quantity'] > 0]

Number of rows with invalid quantities: 3

# **Question 4: What is the total sales revenue generated by the store, and what is the total volume of items sold across the entire dataset (after filtering out anomalies)?**

In [9]:
total_revenue = df_cleaned['Total_Sales'].sum()
total_items = df_cleaned['Quantity'].sum()

print(f"Total Revenue Generated: ${total_revenue:,.2f}")
print(f"Total Items Sold: {int(total_items)}")

Total Revenue Generated: $66,308.00
Total Items Sold: 1443

# **Question 5: Which product name generates the highest total revenue, and which product is ordered the most frequently in terms of total units sold?**

In [10]:
product_summary = df_cleaned.groupby('Product_Name').agg(
    Total_Units_Sold=('Quantity', 'sum'),
    Total_Revenue=('Total_Sales', 'sum')
).sort_values(by='Total_Revenue', ascending=False)

print(product_summary)

              Total_Units_Sold  Total_Revenue
Product_Name
Jacket                   271.0        23085.0
Sneakers                 174.0        11310.0
Dress                    229.0        10355.0
Hoodie                   193.0         9650.0
Jeans                    163.0         6520.0
T-shirt                  181.0         3540.0
Socks pack               232.0         1848.0

# **Question 6: Which geographic region dominates the market in terms of sales revenue, and how does the average transaction value change from region to region?**

In [11]:
region_summary = df_cleaned.groupby('Region')['Total_Sales'].agg(['sum', 'mean', 'count'])
region_summary.columns = ['Total Revenue', 'Average Order Value', 'Order Count']
print(region_summary.sort_values(by='Total Revenue', ascending=False))

        Total Revenue  Average Order Value  Order Count
Region
North         22979.0           140.115854          164
West          22290.0           128.103448          174
South         10377.0           136.539474           76
East          10307.0           135.618421           76

# **Question 7: Who are the top 5 high-value customers based on their cumulative spending, and how many unique orders did each of them place?**

In [12]:
top_customers = df_cleaned.groupby('Customer_Name')['Total_Sales'].agg(['sum', 'count'])
top_customers.columns = ['Total_Spent', 'Total_Orders']
print(top_customers.sort_values(by='Total_Spent', ascending=False).head(5))

               Total_Spent  Total_Orders
Customer_Name
Riya Rao            1350.0             6
Ananya Singh        1118.0             6
Ananya Verma        1115.0             5
Sanya Sharma        1114.0             4
Sanya Joshi         1110.0             6

# **Question 8: How do sales trend over the recorded months? Which specific month or day of the week experiences peak shopping activity?**

In [14]:

df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'])


df_cleaned['Month'] = df_cleaned['Date'].dt.strftime('%B')

monthly_sales = df_cleaned.groupby('Month')['Total_Sales'].sum().sort_values(ascending=False)
print(monthly_sales)

Month
May         16699.0
March       14323.0
April       13847.0
February    11872.0
January      8872.0
Name: Total_Sales, dtype: float64

/tmp/ipykernel_3628/1172685997.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'])
/tmp/ipykernel_3628/1172685997.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Month'] = df_cleaned['Date'].dt.strftime('%B')

# **Question 9: What is the price of the single most expensive item in the dataset, and what is the price of the cheapest item?**

In [15]:
max_price = df['Unit_Price'].max()
min_price = df['Unit_Price'].min()

print("Most expensive item price:", max_price)
print("Cheapest item price:", min_price)

Most expensive item price: 85.0
Cheapest item price: 0.0

# **Question 10: Exactly how many orders were placed from each region (North, South, East, West)?**

In [16]:

order_counts = df['Region'].str.lower().value_counts()
print("Number of orders per region:")
print(order_counts)

Number of orders per region:
Region
west     174
north    166
south     78
east      77
Name: count, dtype: int64